name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Tag
        uses: Instrument/github-tag-action@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          BUMP: major
      - name: Print
        run: echo "${{steps.Tag.outputs.new_tag}}" 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build 
        run: docker build --cache-from ${{ secrets.DOCKER_HUB_USERNAME }}/service1:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/service1 .
        
      - name: Push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/service1
      
