name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 15.13.28
          # you can set branch for semantic-release older than v16.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build 
        run: docker build --cache-from ${{ secrets.DOCKER_HUB_USERNAME }}/service1:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/service1 .
        
      - name: Push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/service1
      
